# Generated by Django 3.2.2 on 2021-07-03 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('cdgrupo', models.AutoField(db_column='cdGrupo', primary_key=True, serialize=False)),
                ('nmgrupo', models.CharField(blank=True, db_column='nmGrupo', max_length=70, null=True)),
            ],
            options={
                'db_table': 'Grupo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('cdloja', models.AutoField(db_column='cdLoja', primary_key=True, serialize=False)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('nmloja', models.CharField(blank=True, db_column='nmLoja', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Loja',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('cdperfil', models.AutoField(db_column='cdPerfil', primary_key=True, serialize=False)),
                ('nmperfil', models.CharField(blank=True, db_column='nmPerfil', max_length=30, null=True)),
            ],
            options={
                'db_table': 'Perfil',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('cdStatus', models.AutoField(db_column='cdStatus', primary_key=True, serialize=False)),
                ('nmStatus', models.CharField(blank=True, db_column='nmStatus', max_length=30, null=True)),
            ],
            options={
                'db_table': 'Status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tipomovimento',
            fields=[
                ('cdtipomovimento', models.AutoField(db_column='cdTipoMovimento', primary_key=True, serialize=False)),
                ('nmtipomovimento', models.CharField(blank=True, db_column='nmTipoMovimento', max_length=70, null=True)),
            ],
            options={
                'db_table': 'TipoMovimento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cdusuario', models.AutoField(db_column='cdUsuario', primary_key=True, serialize=False)),
                ('nmusuario', models.CharField(blank=True, db_column='nmUsuario', max_length=30, null=True)),
                ('senha', models.CharField(blank=True, max_length=50, null=True)),
                ('cdperfil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.perfil')),
            ],
            options={
                'db_table': 'Usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Subgrupo',
            fields=[
                ('cdsubgrupo', models.AutoField(db_column='cdSubGrupo', primary_key=True, serialize=False)),
                ('nmsubgrupo', models.CharField(blank=True, db_column='nmSubGrupo', max_length=70, null=True)),
                ('cdGrupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.grupo')),
            ],
            options={
                'db_table': 'SubGrupo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('cdproduto', models.AutoField(db_column='cdProduto', primary_key=True, serialize=False)),
                ('idproduto', models.IntegerField(blank=True, db_column='idProduto', null=True)),
                ('nmproduto', models.CharField(blank=True, db_column='nmProduto', max_length=70, null=True)),
                ('cdsubgrupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.subgrupo')),
            ],
            options={
                'db_table': 'Produto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('cdmovimentacao', models.AutoField(db_column='cdMovimentacao', primary_key=True, serialize=False)),
                ('dtmovimentacao', models.DateTimeField(auto_now_add=True)),
                ('dtAlteracao', models.DateTimeField(auto_now=True)),
                ('cdloja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.loja')),
                ('cdtipomovimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipomovimento')),
                ('cdusuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.usuario')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.status')),
            ],
            options={
                'db_table': 'Movimentacao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Itemmovimentado',
            fields=[
                ('cditemmovimentado', models.AutoField(db_column='cdItemMovimentado', primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('cdmovimentacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.movimentacao')),
                ('cdproduto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.produto')),
            ],
            options={
                'db_table': 'ItemMovimentado',
                'managed': True,
            },
        ),
    ]
