# Generated by Django 3.2.2 on 2022-05-20 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acesso',
            fields=[
                ('cdacesso', models.AutoField(db_column='cdAcesso', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Acesso',
                'ordering': ['user__username'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('cdgrupo', models.AutoField(db_column='cdGrupo', primary_key=True, serialize=False)),
                ('nmgrupo', models.CharField(blank=True, db_column='nmGrupo', max_length=70, null=True)),
            ],
            options={
                'db_table': 'Grupo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Itemmovimentado',
            fields=[
                ('cditemmovimentado', models.AutoField(db_column='cdItemMovimentado', primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('valorLiquido', models.FloatField()),
            ],
            options={
                'db_table': 'ItemMovimentado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('cdloja', models.AutoField(db_column='cdLoja', primary_key=True, serialize=False)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('nmloja', models.CharField(blank=True, db_column='nmLoja', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Loja',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('cdmovimentacao', models.AutoField(db_column='cdMovimentacao', primary_key=True, serialize=False)),
                ('dtmovimentacao', models.DateTimeField()),
                ('dtAlteracao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Movimentacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('cdOcorrencia', models.AutoField(db_column='cdOcorrencia', primary_key=True, serialize=False)),
                ('dtOcorrencia', models.DateTimeField(auto_now_add=True)),
                ('dsOcorrencia', models.CharField(blank=True, db_column='dsOcorrencia', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Ocorrencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('cdproduto', models.AutoField(db_column='cdProduto', primary_key=True, serialize=False)),
                ('idproduto', models.IntegerField(blank=True, db_column='idProduto', null=True)),
                ('nmproduto', models.CharField(blank=True, db_column='nmProduto', max_length=70, null=True)),
                ('ativo', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], max_length=1)),
                ('vlconv', models.FloatField()),
                ('percPerda', models.FloatField(blank=True, db_column='percPerdaDesc', null=True)),
            ],
            options={
                'db_table': 'Produto',
                'ordering': ['nmproduto'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('cdStatus', models.AutoField(db_column='cdStatus', primary_key=True, serialize=False)),
                ('nmStatus', models.CharField(blank=True, db_column='nmStatus', max_length=30, null=True)),
            ],
            options={
                'db_table': 'Status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subgrupo',
            fields=[
                ('cdsubgrupo', models.AutoField(db_column='cdSubGrupo', primary_key=True, serialize=False)),
                ('nmsubgrupo', models.CharField(blank=True, db_column='nmSubGrupo', max_length=70, null=True)),
            ],
            options={
                'db_table': 'SubGrupo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipomovimento',
            fields=[
                ('cdtipomovimento', models.AutoField(db_column='cdTipoMovimento', primary_key=True, serialize=False)),
                ('nmtipomovimento', models.CharField(blank=True, db_column='nmTipoMovimento', max_length=70, null=True)),
                ('conversao', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], max_length=1)),
            ],
            options={
                'db_table': 'TipoMovimento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoUnidade',
            fields=[
                ('cdUnidade', models.AutoField(db_column='cdUnidade', primary_key=True, serialize=False)),
                ('nmUnidade', models.CharField(blank=True, db_column='nmUnidade', max_length=5, null=True)),
            ],
            options={
                'db_table': 'TipoUnidade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImportaDePara',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('dataImportacao', models.DateField()),
                ('cdLoja', models.IntegerField()),
                ('produtoLoja', models.CharField(max_length=255)),
                ('cdProduto', models.IntegerField()),
            ],
        ),
    ]
