# Generated by Django 3.2.2 on 2022-05-20 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importadepara',
            options={'managed': False},
        ),
    ]
