# Generated by Django 3.2.2 on 2021-07-20 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
    
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('cdOcorrencia', models.AutoField(db_column='cdOcorrencia', primary_key=True, serialize=False)),
                ('dtOcorrencia', models.DateTimeField(auto_now_add=True)),
                ('dsOcorrencia', models.CharField(blank=True, db_column='obs', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Ocorrencia',
                'managed': True,
            },
        ),
      
        migrations.AddField(
            model_name='ocorrencia',
            name='cdMovimentacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.movimentacao'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
