# Generated by Django 3.2.2 on 2021-07-03 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acesso',
            fields=[
                ('cdacesso', models.AutoField(db_column='cdAcesso', primary_key=True, serialize=False)),
                ('cdloja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.loja')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Acesso',
                'managed': True,
            },
        ),
    ]
