# Generated by Django 3.2.2 on 2022-05-20 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_importadepara_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='importadepara',
            table='ImportaDePara',
        ),
    ]
