# Generated by Django 3.2.2 on 2021-07-04 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_movimentacao_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacao',
            name='cdusuario',
        ),
    ]
