# Generated by Django 3.2.2 on 2022-05-21 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_importadepara_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importadepara',
            options={},
        ),
    ]
