# Generated by Django 3.2.2 on 2022-06-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220520_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='importa_de_para',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtimportacao', models.DateField()),
                ('cdloja', models.IntegerField()),
                ('nmprodutocliente', models.CharField(max_length=255)),
                ('cdproduto', models.IntegerField()),
            ],
            options={
                'db_table': 'importa_de_para',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ImportaDePara',
        ),
    ]
